version: '3.8'
services:
  postgresqldb:
    image: postgres
    container_name: my-fav-games-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-fav-games-db
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: